readme update
Zubax/Bloxa pull request #1
Opened 2020-02-26 20:39 UTC by j3qq4hch

A brief description of what Bloxa is is provided

2020-02-27 13:44 UTC, pavel-kirienko commented
- [ ] Пожалуйста, используйте лицензию CC-BY 4.0, как предписано политиками. CC BY-SA непригодна для референса, потому что она запрещает использование этой интеллектуальной собственности в коммерческих проектах. Чтобы не повторяться, обновите, пожалуйста, лицензию в других референсах тоже.
- [ ] Мне кажется, есть смысл рядом со ссылкой на Autodesk Online Gallery указать, что версия по ссылке может отличаться от текущей, или же ссылку можно убрать совсем.
- [ ] Тип химии батареи не указан (у вас подразумевается LiCoO<sub>2</sub>)
- [ ] Не указаны ключевые требования к устройству. Они являются основной составляющей внутренней документации. Они должны отвечать на вопрос "зачем устройство существует?"; сопоставление характеристик устройства с ними должно позволить читателю понять, хорошо ли выполнен проект (т.е., соответствует ли он своим целям). В текущем случае предпосылки были, по меньшей мере, следующими: компактность, дешевизна, простота, отсутствие требований по высокой отказоустойчивости (как следствие, необычный подход к монтажу митохондрика).
- [ ] Размер изображений я предлагаю уменьшить до примерно трети или даже четверти ширины текста, иначе они занимают слишком много места и затрудняют восприятие. Вместо CSS свойства `zoom` вы можете использовать `width` в процентах, например.
- [ ] Исправьте типографику и пунктуацию. Например, перед открывающей скобкой [необходим пробел](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%B5%D0%BB#%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0_%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8_%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D0%B0_%D1%80%D1%8F%D0%B4%D0%BE%D0%BC_%D1%81%D0%BE_%D0%B7%D0%BD%D0%B0%D0%BA%D0%B0%D0%BC%D0%B8_%D0%BF%D1%80%D0%B5%D0%BF%D0%B8%D0%BD%D0%B0%D0%BD%D0%B8%D1%8F_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5). Если элементы списка являются предложениями (у вас являются), ставьте [точку в конце](http://webstyle.sfu-kras.ru/oformlenie-spiskov). Если в документе используются заголовки (у вас используются), то в начале документа должно быть название (`# Bloxa` в вашем случае, или что-то в духе `# Bloxa reference design`, если угодно). Мы не хотим и не можем выполнять за вас работу по вычитке текста и убирать очевиднейшие дефекты вроде "is uses". Пожалуйста, сэкономьте наше время и проведите базовую редактуру самостоятельно. Это касается других PR тоже.

2020-04-03 11:35 UTC, j3qq4hch commented
Изображения исправлены. 
Остальное тоже

2020-04-23 15:04 UTC, pavel-kirienko requested changes

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +* [UAVCAN hardware recommendations](https://uavcan.org/Specification/8._Hardware_design_recommendations/) following
```suggestion
* Compatible with the [UAVCAN hardware design recommendations](https://uavcan.org/specification)
```

poor wording

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +Zubax Bloxa is the most compact ESC design that is possible using Mitochondrik module (at least it seems to be it). The **key design requirements** for BLOXA are:
```suggestion
Zubax Bloxa is arguably the most compact practical ESC design based on the Mitochondrik module. The **key design requirements** for Bloxa are:
```

Better wording; correct spelling: BLOXA --> Bloxa.

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +<p align="center">
```suggestion
```

Let's not overdo it, shall we? This is not HTML, after all; one day they may change the Markdown parser and our nice docs would go haywire. I suggest keeping HTML to the bare minimum, like image scaling and such.

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +* Operating voltage range 4-8S Li-Po (LiCoO<sub>2</sub>) battery (12-34 V)
```suggestion
* Operating voltage range 4-8S Li-ion (LiCoO<sub>2</sub>) battery (12-34 V)
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +* RC PWM input available on test-pads (requires soldering)
```suggestion
* RC PWM input available on test pads (requires soldering)
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +The main advantage of BLOXA is its miniature size. To achieve it, a novel Mitochondrik mounting technique was used.
```suggestion
The main advantage of Bloxa is its miniature size. To achieve it, a novel Mitochondrik mounting technique is used.
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +<img src="pics/drawing.png" alt="drawing"  width = "80%"/>
```suggestion
<img src="pics/drawing.png" alt="drawing"  width = "80%"/>
</p>
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +<img src="pics/construction.png"  width = "50%"/>
```suggestion
<img src="pics/construction.png"  width = "50%"/>
</p>
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +Mitochondrik is mounted on the power stage PCB using intermediary 2mm thick PCB that basically serves as a connector. Soldering is done using edge connectors on the Mitochondrik, the intermediary  PC
```suggestion
Mitochondrik is mounted on the power stage PCB using an intermediary 2mm thick PCB that basically serves as a connector.
Soldering is done using the edge connectors on the Mitochondrik, the intermediary  PCB, and the power stage PCB in the plane perpendicular to the PCB planes. 
Also, one of the RF shields on the Mitochondrik had to be removed (please contact Zubax Robotics for ordering).
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +Of course, this mounting technique seems questionable from the vibration resistance point of view, but it allows for the smallest PCB design possible. Bloxa has no strict reliability requirements, so
```suggestion
High-reliability designs may prefer to avoid such unconventional approaches to ensure predictable mechanical characteristics.
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +Current shunt value is 10 mOhm.
```suggestion
The current shunt value is 10 mOhm.
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +The bulk capacitor bank is formed with 3 [180 µF  aluminum electrolytic capacitors](https://www.digikey.com/products/en?keywords=565-4066-ND) from [ United Chemi-Con](https://www.digikey.com/en/suppl
```suggestion
The bulk capacitor bank is formed with 3 [180 µF aluminum electrolytic capacitors](https://www.digikey.com/products/en?keywords=565-4066-ND) from [United Chemi-Con](https://www.digikey.com/en/supplier-centers/u/united-chemi-con).
```

2020-04-23 15:04 UTC, pavel-kirienko commented on README.md
> +Overcurrent protection trip value is set to 35 A.
```suggestion
The overcurrent protection trip value is set to 35 A. 
```

2020-04-23 15:36 UTC, pavel-kirienko approved these changes

2020-04-23 15:36 UTC, merged